# WARNING - Generated by {fusen} from dev/flat_my_package.Rmd: do not edit by hand # nolint: line_length_linter.

testthat::test_that("cube works correctly", {
  testthat::expect_equal(cube(2), 8)
  testthat::expect_equal(cube(0), 0)
  testthat::expect_error(cube("b"), "x must be numeric")
})
