# WARNING - Generated by {fusen} from dev/flat_my_package.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculate the Cube of a Number
#' 
#' @param x A numeric value
#' @return The cube of x
#' @export
#' @examples
#' cube(3)
#' cube(2)  # Returns 8
#' cube(4)  # Returns 64
cube <- function(x) {
  if (!is.numeric(x)) stop("x must be numeric")
  x^3
}
