# WARNING - Generated by {fusen} from dev/flat_my_package.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculate the Square of a Number
#' 
#' @param x A numeric value
#' @return The square of x
#' @export
#' @examples
#' square(5)
#' square(5)  # Returns 25
#' square(3)  # Returns 9
square <- function(x) {
  if (!is.numeric(x)) stop("x must be numeric")
  x^2
}
